insert into krusty.recipes (Cookie_name, Ingredient_name, Amount, rUnit)
values  ('Nut cookie', 'Bread crumbs', 125, 'g'),
        ('Almond delight', 'Butter', 400, 'g'),
        ('Amneris', 'Butter', 250, 'g'),
        ('Berliner', 'Butter', 250, 'g'),
        ('Nut ring', 'Butter', 450, 'g'),
        ('Tango', 'Butter', 200, 'g'),
        ('Berliner', 'Chocolate', 50, 'g'),
        ('Nut cookie', 'Chocolate', 50, 'g'),
        ('Almond delight', 'Chopped almonds', 279, 'g'),
        ('Almond delight', 'Cinnamon', 10, 'g'),
        ('Nut cookie', 'Egg Whites', 350, 'ml'),
        ('Amneris', 'Eggs', 250, 'g'),
        ('Berliner', 'Eggs', 50, 'g'),
        ('Nut cookie', 'Fine-ground nuts', 750, 'g'),
        ('Almond delight', 'Flour', 400, 'g'),
        ('Berliner', 'Flour', 350, 'g'),
        ('Nut ring', 'Flour', 450, 'g'),
        ('Tango', 'Flour', 300, 'g'),
        ('Nut cookie', 'Ground, roasted nuts', 625, 'g'),
        ('Berliner', 'Icing sugar', 100, 'g'),
        ('Nut ring', 'Icing sugar', 190, 'g'),
        ('Amneris', 'Marzipan', 750, 'g'),
        ('Amneris', 'Potato starch', 25, 'g'),
        ('Nut ring', 'Roasted, chopped nuts', 225, 'g'),
        ('Tango', 'Sodium bicarbonate', 4, 'g'),
        ('Almond delight', 'Sugar', 270, 'g'),
        ('Nut cookie', 'Sugar', 375, 'g'),
        ('Tango', 'Sugar', 250, 'g'),
        ('Tango', 'Vanilla', 2, 'g'),
        ('Berliner', 'Vanilla sugar', 5, 'g'),
        ('Amneris', 'Wheat flour', 25, 'g');